In [2]:
#original data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
#profit = revenue - expenses

In [23]:
import numpy as np
# converting original data lists into arrays
aRevenue = np.array(revenue)
aExpenses = np.array(expenses)

# creating named month reference for final reporting
aMonths = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
#print(aRevenue)
#print(aExpenses)
#print(aMonths)

In [24]:
#using the subtract method from NumPy to calculate << profits >>
np.subtract(aRevenue,aExpenses)

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [25]:
#using the multiply method from NumPy to calculate *<< profit after tax >>
profitAfterTax = np.subtract(np.subtract(aRevenue,aExpenses),np.subtract(aRevenue,aExpenses) * 0.3)
profitAfterTax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [45]:
#using the divide method from NumPy to calculate << profit margin >>
profitMargin = (np.divide(profitAfterTax,aRevenue) * 100).round(2)
profitMargin

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [50]:
np.max(profitMargin)
np.min(profitMargin)

-30.14

In [49]:
#finding best month

nBestMonth, = np.where(profitMargin == np.max(profitMargin))
aBestMonth = aMonths[nBestMonth[0]]
print(aBestMonth, '(',nBestMonth[0],')')

June ( 5 )


In [52]:
#finding worst month

nWorstMonth, = np.where(profitMargin == np.min(profitMargin))
aWorstMonth = aMonths[nWorstMonth[0]]
print(aWorstMonth, '(',nWorstMonth[0],')')

March ( 2 )


In [5]:
#calculating profits and profits after tax

aProfit = aRevenue - aExpenses
aTax = aProfit * 0.3
aProfitTax = aProfit - aTax
print('Profit: ', aProfit)
print('Profit after tax: ', aProfitTax) #what to do with negative profit values? do taxes apply before calculating profits?
aProfitMargin = ( ( aProfitTax / aRevenue ) * 100 ).round(2) #we can apply the round() method after calculating the values for the array!
 
print('Profit Margin Rounded: ', aProfitMargin)
aProfitMean = aProfitTax.mean().round(2)
print('Profit Mean: ', aProfitMean)

Profit:  [ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]
Profit after tax:  [ 1765.869  1337.973 -2595.453 -2040.017  -419.944  5085.668  5747.385
  2761.479  2329.873 -1567.055   461.72   8140.678]
Profit Margin Rounded:  [ 12.12  17.59 -30.14 -22.23  -5.21  62.74  49.99  28.28  22.61 -10.9
   4.31  52.75]
Profit Mean:  1750.68


In [53]:
#finding good months
xGoodMonths = aProfitTax[ aProfitTax > aProfitMean ] #xGoodMonths selects the values from aProfitTax which are higher than average
#print(nGoodMonths)
#nGoodMonths = np.array[]
nGoodMonths, = np.where(np.isin(aProfitTax, xGoodMonths)) #nGoodMonths selects the index of the values from xGoodMonths
print('NGood Months: ', nGoodMonths)
type(nGoodMonths)

NGood Months:  [ 0  5  6  7  8 11]


numpy.ndarray

In [54]:
aGoodMonths = aMonths[nGoodMonths]
#print(np.where(aGoodMonths))
print('aGoodMonths', aGoodMonths) #ainda acha só o primeiro...

TypeError: only integer scalar arrays can be converted to a scalar index

In [82]:
#finding bad months
nBadMonths = aProfitTax[ aProfitTax < aProfitMean ]
print(nBadMonths)

[ 1337.973 -2595.453 -2040.017  -419.944 -1567.055   461.72 ]


In [42]:
#finding best month

nBestMonth, = np.where(aProfitMargin == aProfitMargin.max())
print(nBestMonth[0])
aBestMonth = aMonths[nBestMonth[0]]
print(aBestMonth)

5
June


In [43]:
#finding worst month
nWorstMonth, = np.where(aProfitMargin == aProfitMargin.min())
print(nWorstMonth[0])
aWorstMonth = aMonths[nWorstMonth[0]]
print(aWorstMonth)

2
March
