<a href="https://colab.research.google.com/github/alexandrepereiraarq/PytonDataAnalysis/blob/master/PyA_Z_3_23_Section_3_Homework_numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#original data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [0]:
#profit = revenue - expenses

In [0]:
import numpy as np
# converting original data lists into arrays
aRevenue = np.array(revenue)
aExpenses = np.array(expenses)

# creating named month reference for final reporting
aMonths = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
#print(aRevenue)
#print(aExpenses)
#print(aMonths)

In [4]:
#using the subtract method from NumPy to calculate << profits >>
np.subtract(aRevenue,aExpenses)

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [5]:
#using the multiply method from NumPy to calculate *<< profit after tax >>
profitAfterTax = np.subtract(np.subtract(aRevenue,aExpenses),np.subtract(aRevenue,aExpenses) * 0.3)
profitAfterTax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [6]:
#using the divide method from NumPy to calculate << profit margin >>
profitMargin = (np.divide(profitAfterTax,aRevenue) * 100).round(2)
profitMargin

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [7]:
#@title Default title text
np.max(profitMargin)

62.74

In [8]:
np.min(profitMargin)

-30.14

In [9]:
#finding best month

nBestMonth, = np.where(profitMargin == np.max(profitMargin))
aBestMonth = aMonths[nBestMonth[0]]
print(aBestMonth, '(',nBestMonth[0],')')

June ( 5 )


In [10]:
nBestMonth

array([5])

In [11]:
#finding worst month

nWorstMonth, = np.where(profitMargin == np.min(profitMargin))
aWorstMonth = aMonths[nWorstMonth[0]]
print(aWorstMonth, '(',nWorstMonth[0],')')

March ( 2 )


---

In [0]:
#from now on nothing works...

In [13]:
xGoodMonths = profitAfterTax[ profitAfterTax > profitAfterTax.mean() ] #xGoodMonths selects the values from aProfitTax which are higher than average
xGoodMonths

array([1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678])

In [14]:
nGoodMonths = np.where(profitAfterTax > profitAfterTax.mean())
nGoodMonths[0]

array([ 0,  5,  6,  7,  8, 11])

In [15]:
# honestly, I can't understand why the line below throws a TypeError: only integer scalar arrays can be converted to a scalar index
#aGoodMonths = aMonths[nGoodMonths[0]]
#
# List comprehensions FTW!
aGoodMonths = [aMonths[x] for x in nGoodMonths[0]]
aGoodMonths

['January', 'June', 'July', 'August', 'September', 'December']

In [17]:
nBadMonths = np.where(profitAfterTax < profitAfterTax.mean())
# List comprehensions FTW!
aBadMonths = [aMonths[x] for x in nBadMonths[0]]
aBadMonths

['February', 'March', 'April', 'May', 'October', 'November']

In [0]:
#finding good months
xGoodMonths = profitAfterTax[ profitAfterTax > profitAfterTax.mean() ] #xGoodMonths selects the values from aProfitTax which are higher than average
print(xGoodMonths)

nGoodMonths = np.isin(profitAfterTax, xGoodMonths)
print(nGoodMonths)
aGoodMonths = aMonths[nGoodMonths]

print(aGoodMonths)
#for i in range(0, len(xGoodMonths)):
 #   nGoodMonths.append()

[1765.869 5085.668 5747.385 2761.479 2329.873 8140.678]
[ True False False False False  True  True  True  True False False  True]


TypeError: only integer scalar arrays can be converted to a scalar index

In [0]:
#nGoodMonths selects the index of the values from xGoodMonths
nGoodMonths, = np.where(np.isin(profitAfterTax, xGoodMonths))
print('NGood Months: ', nGoodMonths)
type(nGoodMonths)

NGood Months:  [ 0  5  6  7  8 11]


numpy.ndarray

---

In [0]:
#reference code from https://stackoverflow.com/questions/3179106/python-select-subset-from-list-based-on-index-set

In [0]:
#Using numpy:
property_a = np.array([545., 656., 5.4, 33.])
property_b = np.array([ 1.2,  1.3, 2.3, 0.3])
good_objects = [False, True, False, True]
good_indices = [0, 3]
property_asel = property_a[good_objects]
property_bsel = property_b[good_indices]

In [0]:
#my own tests
print(property_asel)
print(property_bsel)
property_bsela = property_b[good_objects]
print('using A to select from B', property_bsela)

[656.  33.]
[1.2 0.3]
using A to select from B [1.3 0.3]


In [0]:
#Using a list comprehension and zip it:
property_a = [545., 656., 5.4, 33.]
property_b = [ 1.2,  1.3, 2.3, 0.3]
good_objects = [True, False, False, True]
good_indices = [0, 3]
property_asel = [x for x, y in zip(property_a, good_objects) if y]
property_bsel = [property_b[i] for i in good_indices]

---

In [0]:
#old code

In [0]:
#finding good months
xGoodMonths = aProfitTax[ aProfitTax > aProfitMean ] #xGoodMonths selects the values from aProfitTax which are higher than average
#print(nGoodMonths)
#nGoodMonths = np.array[]
nGoodMonths, = np.where(np.isin(aProfitTax, xGoodMonths)) #nGoodMonths selects the index of the values from xGoodMonths
print('NGood Months: ', nGoodMonths)
type(nGoodMonths)

NameError: name 'aProfitTax' is not defined

In [0]:
aGoodMonths = aMonths[nGoodMonths]
#print(np.where(aGoodMonths))
print('aGoodMonths', aGoodMonths) #ainda acha só o primeiro...

TypeError: only integer scalar arrays can be converted to a scalar index

In [0]:
#finding bad months
nBadMonths = aProfitTax[ aProfitTax < aProfitMean ]
print(nBadMonths)

[ 1337.973 -2595.453 -2040.017  -419.944 -1567.055   461.72 ]


In [0]:
#finding best month

nBestMonth, = np.where(aProfitMargin == aProfitMargin.max())
print(nBestMonth[0])
aBestMonth = aMonths[nBestMonth[0]]
print(aBestMonth)

5
June


In [0]:
#finding worst month
nWorstMonth, = np.where(aProfitMargin == aProfitMargin.min())
print(nWorstMonth[0])
aWorstMonth = aMonths[nWorstMonth[0]]
print(aWorstMonth)

2
March
